# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  fileSystems."/" = { 
      device = "/dev/disk/by-uuid/0a81878c-2e28-4c73-8589-96446e93c6a4";
      fsType = "ext4";
  };
  fileSystems."/home" = { 
      device = "/dev/disk/by-uuid/a308663e-a262-448d-bfdf-16cd450cf246";
      fsType = "btrfs";
  };


  fileSystems."/boot" ={ 
    device = "/dev/disk/by-uuid/B581-AD78";
      fsType = "vfat";
  };

  swapDevices = [
    { 
      device = "/dev/disk/by-uuid/0b1951d8-e365-4f7a-a072-10c383407677";
    }
  ];

  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    initrd = {
      # The set of kernel modules in the initial ramdisk used during the boot process.
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      # List of modules that are always loaded by the initrd.
      kernelModules = [
        "evdi"
      ];
      secrets = {
        "/crypto_keyfile.bin" = null;
      };
      luks.devices = {
        # Enable swap on luks
        "luks-7f34b0ef-aa8a-412a-933c-a42414371fad".device = "/dev/disk/by-uuid/7f34b0ef-aa8a-412a-933c-a42414371fad";
        "luks-7f34b0ef-aa8a-412a-933c-a42414371fad".keyFile = "/crypto_keyfile.bin";
        "luks-266811b8-953c-4007-9bbd-ed9a009f72ed".device = "/dev/disk/by-uuid/266811b8-953c-4007-9bbd-ed9a009f72ed";
        "luks-361b9e74-4d96-49fa-9243-1676586caed0".device = "/dev/disk/by-uuid/361b9e74-4d96-49fa-9243-1676586caed0";
      };
    };
    runSize = "20%";
    # The set of kernel modules to be loaded in the second stage of the boot process
    kernelModules = [ 
        "kvm-intel"
    ];
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    plymouth = {
      enable = true;
      #themePackages = [ nixos-boot ];
      #theme = "load_unload";
    };
    kernel.sysctl = {
      "vm.swappiness" = 10;
    };
    # A list of additional packages supplying kernel modules.
    extraModulePackages = [
      # Add other modules here if you have any
      config.boot.kernelPackages.evdi
    ];
  };

  # host-specific packages
  environment.systemPackages = with pkgs; [
    displaylink # DisplayLink DL-7xxx, DL-6xxx, DL-5xxx, DL-41xx and DL-3x00 Driver for Linux
  ];

  #services.displaylink.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1.useDHCP = lib.mkDefault true
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
