{ config, pkgs, ... }:
{
  networking = {
    hostName = "envy"; # Define your hostname

    interfaces = {
      enp0s20f0u5.ipv4.addresses = [{
        address = "10.0.0.10";
        prefixLength = 16;
      }];
    };

    # 🌟 Define the default gateway IP address 🌟
    defaultGateway = "10.0.0.1";

    firewall = {
      allowedTCPPorts = [
        80
        443
        3003
        8096
      ];
      # checkReversePath = false;
      allowedUDPPorts = [
       53
      ];
    };

    nameservers = [
      "127.0.0.1:51"
      "[::1]:51"
    ];
  };

  environment.etc."resolv.conf".text = ''
    # Generated by environment.etc (NixOS static DNS fix)
    "127.0.0.1:51"
    "[::1]:51"
  '';

  boot.kernel.sysctl = {
    "net.ipv4.ip_forward" = 1;
    "net.ipv4.ip_unprivileged_port_start" = 0;
  };

  services.dnscrypt-proxy2 = {
    settings = {
      listen_addresses = [
        "127.0.0.1:51"
        "[::1]:51"
      ];
    };
  };
}
