{ config, lib, pkgs, ... }:
{
  networking = {
    interfaces = {
      enp0s20f0u5.ipv4.addresses = [{
        address = "10.0.0.10";
        prefixLength = 16;
      }];
    };

    # 🌟 Define the default gateway IP address 🌟
    defaultGateway = "10.0.0.1";

    firewall = {
      allowedTCPPorts = [
        80
        443
        3003
        8096
      ];
      # checkReversePath = false;
      allowedUDPPorts = [
       53
      ];
    };

    nameservers = [
      "127.0.0.1:51"
      "[::1]:51"
    ]; 
    # Disable the conflict-prone options
    resolvconf.enable = lib.mkForce false;

    networkmanager = {
      enable = lib.mkForce false;
      dns = lib.mkForce "none";
    };
  };

  services.resolved = {
    enable = lib.mkForce false;
    extraConfig = ''
      DNSStubListener=no
    '';
  };

  environment.etc."resolv.conf".text = lib.mkForce ''
    # Generated by environment.etc (NixOS static DNS fix)
    nameserver 127.0.0.1
    nameserver ::1
    # Trust the AD (authentic data) flag and use EDNS(0)
    options trust-ad edns0
  '';

  boot.kernel.sysctl = {
    "net.ipv4.ip_forward" = 1;
    "net.ipv4.ip_unprivileged_port_start" = 0;
  };
}
